<a href="https://colab.research.google.com/github/Syedaly/samples/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello, learning PyTorch!")

Hello, learning PyTorch!


In [2]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

2.1.0+cu118


# New Section

In [3]:
## What is Tensors - way of rep data - numeric data
## creating Tensors

## https://pytorch.org/docs/stable/tensors.html

In [5]:
# scalar
scalar = torch.tensor(7)
scalar.ndim
scalar.item()
scalar

tensor(7)

In [7]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [11]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX.ndim

2

In [16]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                      [3, 6, 9],
                      [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

why random tensors:

https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb

machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [26]:
random_tensors = torch.rand(2, 5)
random_tensors

tensor([[0.0146, 0.2737, 0.1527, 0.0447, 0.9999],
        [0.8411, 0.4955, 0.6389, 0.8318, 0.5667]])

In [25]:
random_tensors.ndim

3

In [29]:
random_image_tensors = torch.rand(size=(224, 224, 3))
random_image_tensors.shape, random_image_tensors.ndim

(torch.Size([224, 224, 3]), 3)

**Zeros and ones**

create a tensor of  all zeros
Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

Let's create a tensor full of zeros with torch.zeros()

Again, the size parameter comes into play.

In [31]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype

torch.float32

In [34]:
### create a range of tensors of range

In [41]:
arange1 = torch.arange(start=1, end=2000, step=100)
arange1

tensor([   1,  101,  201,  301,  401,  501,  601,  701,  801,  901, 1001, 1101,
        1201, 1301, 1401, 1501, 1601, 1701, 1801, 1901])

In [42]:
### creating tensors like
tens = torch.zeros_like(input=arange1)
tens

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
### tensor datatypes
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded; whether or not track gradients tensor opera

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [45]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [50]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

**Basic operations**

In [3]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [4]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [5]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [6]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [7]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [8]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


Finding the min, max, mean, sum, etc (aggregation)

In [21]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [11]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [22]:
# Returns index of max and min values
print(f"Index where max value occurs: {x.argmax()}")
print(f"Index where min value occurs: {x.argmin()}")

Index where max value occurs: 9
Index where min value occurs: 0


**Reshaping, stacking, squeezing and unsqueezing**

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

In [25]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]), torch.float32)

In [31]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [32]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [33]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [35]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [36]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [37]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [38]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [2]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [3]:
print(x[1][2])

tensor(6)


In [4]:
x[0][1] = 8

In [5]:
x

tensor([[1, 8, 3],
        [4, 5, 6]])

In [6]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [7]:
x[:, 0]

tensor([[1, 2, 3]])

In [20]:
x[:, 1:, 0]

tensor([[4, 7]])